#!/bin/bash

set -e

NOMAD_VERSION=0.4.1
CONSUL_VERSION=0.7.0

DEV=ens4v1
ADDR=$(ip addr show dev $DEV | grep -oP 'inet \K[0-9.]+')
ZONE=$(curl -s --header 'Metadata-Flavor: Google' http://metadata.google.internal/computeMetadata/v1/instance/zone | cut -f4 -d/)
REGION=$(echo $ZONE | cut -f1-2 -d-)

install -d /opt/bin
wget -q -O /opt/nomad_${NOMAD_VERSION}_linux_amd64.zip https://releases.hashicorp.com/nomad/${NOMAD_VERSION}/nomad_${NOMAD_VERSION}_linux_amd64.zip
unzip -o -d /opt/bin /opt/nomad_${NOMAD_VERSION}_linux_amd64.zip
chmod 755 /opt/bin/nomad

cat > /tmp/nomad.conf << EOF
region = "$REGION"
datacenter = "$ZONE"

bind_addr = "0.0.0.0"
advertise {
    http = "$ADDR:4646"
    rpc = "$ADDR:4647"
    serf = "$ADDR:4648"
}

enable_debug = true
enable_syslog = true
syslog_facility = "LOCAL0"
log_level = "DEBUG"

data_dir = "/var/local/nomad"

disable_update_check = false
disable_anonymous_signature = false

leave_on_interrupt = false
leave_on_terminate = false

client {
  enabled = true

  servers = ["localhost:4647"]
  node_class = "system"
  meta {
    zone = "$ZONE"
    region = "$REGION"
  }
  network_interface = "$DEV"
  network_speed = 1000
}

server {
  enabled = true
  bootstrap_expect = 3
  num_schedulers = 1
}
EOF

cat > /etc/systemd/system/nomad.service << EOF
[Unit]
Description=Nomad Agent
After=docker.service
[Service]
TimeoutStartSec=0
ExecStart=/opt/bin/nomad agent -config=/tmp/nomad.conf
[Install]
WantedBy=multi-user.target
EOF

systemctl enable nomad
systemctl start nomad

install -d /var/lib/consul
wget -q -O /opt/consul_${CONSUL_VERSION}_linux_amd64.zip https://releases.hashicorp.com/consul/${CONSUL_VERSION}/consul_${CONSUL_VERSION}_linux_amd64.zip
unzip -o -d /opt/bin /opt/consul_${CONSUL_VERSION}_linux_amd64.zip
chmod 755 /opt/bin/consul

cat > /etc/systemd/system/consul.service << EOF
[Unit]
Description=Consul Agent
After=docker.service
[Service]
TimeoutStartSec=0
ExecStart=/opt/bin/consul agent -server \
  -bootstrap-expect=3 \
  -advertise=$ADDR \
  -bind=0.0.0.0 \
  -client=0.0.0.0 \
  -data-dir=/var/lib/consul \
  -datacenter=$REGION \
  -ui
[Install]
WantedBy=multi-user.target
EOF

systemctl enable consul
systemctl start consul
