#!/bin/bash

set -e

DEV=ens4v1
ADDR=$(ip addr show dev $DEV | grep -oP 'inet \K[0-9.]+')
ZONE=$(curl -s --header 'Metadata-Flavor: Google' http://metadata.google.internal/computeMetadata/v1/instance/zone | cut -f4 -d/)
REGION=$(echo $ZONE | cut -f1-2 -d-)

install -d /opt/bin
wget -q -O /tmp/nomad.zip https://releases.hashicorp.com/nomad/0.4.1/nomad_0.4.1_linux_amd64.zip
unzip -o -d /opt/bin /tmp/nomad.zip
chmod 755 /opt/bin/nomad

cat > /tmp/nomad.conf << EOF
region = "$REGION"
datacenter = "$ZONE"

bind_addr = "0.0.0.0"
advertise {
    http = "$ADDR:4646"
    rpc = "$ADDR:4647"
    serf = "$ADDR:4648"
}

enable_debug = true
enable_syslog = true
syslog_facility = "LOCAL0"
log_level = "DEBUG"

data_dir = "/var/local/nomad"

disable_update_check = false
disable_anonymous_signature = false

leave_on_interrupt = false
leave_on_terminate = false

client {
  enabled = true

  servers = ["localhost:4647"]
  node_class = "system"

  network_interface = "$DEV"
  network_speed = 1000
}

server {
  enabled = true
  bootstrap_expect = 3
  num_schedulers = 1
#  retry_join = [ "nomad-01", "nomad-02", "nomad-03" ]
}
EOF

cat > /etc/systemd/system/nomad.service << EOF
[Unit]
Description=Nomad Agent
After=docker.service
[Service]
TimeoutStartSec=0
ExecStart=/opt/bin/nomad agent -config=/tmp/nomad.conf
[Install]
WantedBy=multi-user.target
EOF

systemctl enable nomad
systemctl start nomad
